version: '3.8'
services:
  web:
    build: ../../apps/web
    ports:
      - "${WEB_PORT:-3000}:3000"
    env_file:
      - ../../.env
    volumes:
      - ../../:/workspace
    working_dir: /workspace/apps/web
  command: npm run dev
  api:
    build: ../../apps/api
    ports:
      - "${API_PORT:-4000}:4000"
    env_file:
      - ../../.env
    volumes:
      - ../../:/workspace
    working_dir: /workspace/apps/api
  command: npm run dev
  worker:
    build: ../../apps/worker
    ports:
      - "${WORKER_PORT:-5000}:5000"
    env_file:
      - ../../.env
    volumes:
      - ../../:/workspace
    working_dir: /workspace/apps/worker
  command: npm run dev